// Generado: miniaturas de 16px incrustadas para pintar el plato antes de que baje la foto.
export const FUMANCHU_BLUR: Record<string, string> = {
  "/carta/fumanchu/hero-wok.webp":
    "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAsAA8BgJbACdADdlzsfBUAA/vNME1bQDyuDPaT4LYS0dhWpL9D+Vv2n8hUvXXc0qf7HySzRVGbmbZF+tLCwbihs/oI6tx5UsK74X18AAA==",
  "/carta/fumanchu/hostess.webp":
    "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQAgCdASoQABAAA8BgJbACdEfq2P+CTRv4y0AA/u6hVw2kmlT4/30cno5easqcj0y8owWwE5JMEyRVb1vt5zjeUDjL+79rTVj157MTGmaEIZHZ92gUTk3S8XSI/+BuMoAF8OSpSQUAAA==",
  "/carta/fumanchu/logo-original.webp":
    "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAgCdASoQABAAA8BgJbACdLoAAwhzUMNUAP7LGlxcyYII+e3I27L+N5vDmc3/0KLvCD/+J6sIg//ihdD9OUOgAAA=",
  "/carta/fumanchu/logo.webp":
    "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAwAgCdASoQABAAA8BgJbACdLoAAwhzULYKAAD+2L8IUPRvCC7hm6wj9O3+7E6sOQCn/89VB0R/+wpNGQ/lwO+xyrAAAA==",
  "/carta/fumanchu/mascot.webp":
    "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACQAgCdASoQABAAA8BgJbACdFQA5/8D2GcVp9TjAAD+6/xQFuFtOQX1zfDk2JUVAmM5SMDJH3Sn6Z0iksPdURPvZirw0/+re1wsR8ncY9S90+2NQriZ2GwA",
  "/carta/fumanchu/mesa.webp":
    "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAwAgCdASoQAAsAA8BgJYwCdAED/Vx2R+8AAAD+9fC1lHaObK4sBs7M8oXw8wHFDswNcY4Q6mTkoNGw9vZDyzl0AAA=",
  "/carta/fumanchu/plato-aero-pollo.webp":
    "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAsAA8BgJbACdAEfbnxVhAAAAP7qOBm55g+xckv2JwkvestB4p8QYgGVd34muRY8zpfrYne7QWcDJHlQe3LA93nCiw3P6RakW1K+6gAAAA==",
  "/carta/fumanchu/plato-aeropuerto.webp":
    "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACQAgCdASoQAAsAA8BgJbACdH8G6gA84duH63ABAAD+8zXK9yOusf4OZo7WPIO9HE6Ci1K16UH7hzpaaBVfzIyA/vs9tcxhPgc4WV73Ah7WeoqSJk+aFUCds1PjSZ4/8dwQAA==",
  "/carta/fumanchu/plato-chaufa-chancho.webp":
    "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAsAA8BgJagCdAEf57/uyTGspAD+6V+0SZtjaroMjBKvGYctI7LibwtRdp3S4uYxND75+8GdRcgaRNMAs9zOfYXv7W1Ry7XJpWM/WAA=",
  "/carta/fumanchu/plato-chaufa-especial.webp":
    "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAQCdASoQAAsAA8BgJbACdABql7T3QAD+9b3q01xTCjznaO77dvOH/cVaeK4FCtfUXA+jIOZx90YfG1vIA7twpymAaQ5fKGRL+uC2no7ZTNky22tYxi916P5IvAAA",
  "/carta/fumanchu/plato-chaufa-pollo.webp":
    "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoQAAsAA8BgJbACdAEQz6ZLSAD+8YUclPn4skx6K+4EJgTY0suS5GZUMu+YK1J5PNy+cqJ/219SW9sfAWlhln0gGfyaVsAA",
  "/carta/fumanchu/plato-chijaukay.webp":
    "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAsAA8BgJbACdADbZbs7TwAA/veHOwV67BXOFclQHsHBWWLD4WE1SiFtc2S9gqIiKM3j6JJ5gp02DumWkb2j/let9QAA",
  "/carta/fumanchu/plato-cholon.webp":
    "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQAAsAA8BgJZgCdAEQUBbPPkKAAP7b678hsnKcp3Wk4Ri2POBlT4RO6dW17nqN1geEdALk49Mml4H8yi/Z7l7Tqhk6d5gGwflmkyE41fDodIAZAAA=",
  "/carta/fumanchu/plato-chunli.webp":
    "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAsAA8BgJZACdADcrOqFOoAAAP6FG/rNArZLyN7zIdcgTwNlBJVjp4DDRU1fdhND2GJaFMCOOG5xa/fU0i+dKB/mPFm+8QKAAA==",
  "/carta/fumanchu/plato-combo-especial.webp":
    "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABwAgCdASoQAAsAA8BgJbACdGaAAsmuYDgMZt4AAP7zTKsBH5gznZzXPcXWbuV8IBR3nvjRCT+hi4PDKRbseGURLEKm8nyPjZZ+prO2CElnnWBVL4T1DmpAwKc3ChRAAAA=",
  "/carta/fumanchu/plato-combo-pollo.webp":
    "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQAgCdASoQAAsAA8BgJbACdAYtLyKllXkq4kAA/vG6a74Too5o7wBDIi/rlmjWF1qlOrxsqm1jwNs8vJ+NRI4mrugcweLrBpQpndoH5XaVDIeoewXJdvpaHPr0tc+J946iAAAA",
  "/carta/fumanchu/plato-kamlu.webp":
    "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQAgCdASoQAAsAA8BgJbACdAEUekFRS5GAAP7zVP7qZNKYrfZsuOJvZfdjIRmz71xr8dNkm59L+BKfpynkTfNDAHQDZZXt0rzcsF2P59r1RMN/jU1YRAyAO9G0v7LNTNAB0ZEUliZM1JsgAAA=",
  "/carta/fumanchu/plato-lemonkay.webp":
    "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQAAsAA8BgJbACdADJ4U2ElAAA/u+iXmx7z3MtzPPDVFvBjptp84uZ53ql36e8uEmUdUvupLUwsaYtWYJXaSpHziSCan383lMeF2OAeFeJNUVxO79DLgAA",
  "/carta/fumanchu/plato-mango.webp":
    "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoQAAsAA8BgJbACdADN1HwAAP7tD/+rEKGie0F9qFaMzggcBhFiEEXSOZwlNcZG8l+uuQJWiX1HIAR3tfpnvOuyE38bmhJZoLu5DKwA",
  "/carta/fumanchu/plato-rollitos.webp":
    "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQAAsAA8BgJbACdAD19qK43owA/uyYs0pq3yby+mtL8UAApyRf93NEUZrHrKMXxjThZmAYU6z40X9T+3KrdIg9dItuLkPCp62XrCSbNFAZrsUi9MnAAAAA",
  "/carta/fumanchu/plato-saltado.webp":
    "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAsAA8BgJQBOgBt1qftjgAD+9tqiYhyZomhOTVDS6rnkjkLYRtYF4mOImJlZ5th/qv07gJkX8AAA",
  "/carta/fumanchu/plato-siumai.webp":
    "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoQAAsAA8BgJbACdAD0unWmYvrQAAD+0X69uHWpMVT9/aErwBz9s92M+x/7jJGkDUovzXRJa3ud/QT6qRcCgTui8xmPg0uGuXEPkdAg2bIAAA==",
  "/carta/fumanchu/plato-sopa-especial.webp":
    "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAsAA8BgJagCdAEPDXtUI7ZgAP712t5Mi5Va5c4dYMpPjRmLE58TAUq/b9GzJR//ZTr5T2uniJFDi+bbT0Um/7W2WUfzJnfWAAAA",
  "/carta/fumanchu/plato-sopa-wantan.webp":
    "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAsAA8BgJbACdADp/neYzhgAAP70srQuAkT7LsafUOgIyzXjJRYZ4qYOlpVSy9yk6q7Z07lBTlwZMNrIPvf5NLekzfOMSe4SkLBamcAAAA==",
  "/carta/fumanchu/plato-sopa.webp":
    "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAsAA8BgJYgCdAEf+Oo1A94AAP7xrIX9CuG/AjRGTgDssLBWcwrDF419EQo+iDi7x43bSedtr4MScF5Q2009lZCoCd9gAAA=",
  "/carta/fumanchu/plato-tallarin-pollo.webp":
    "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAsAA8BgJbACdADwof4lw0AA/vFQnZFhZy/ge2uC6C7/dbKY62wIOitxSnPzNwD6wmA2hXaO3vyPAAA=",
  "/carta/fumanchu/plato-tallarin.webp":
    "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAAsAA8BgJbACdACH9nA4AAD+9dzH+c416FSEbWpasDbVTL+BaURpchKijs9IWiDw9ZdF7P5LUPKFPBGrx7fG1x4OT1y6xZoJZnKeuAA=",
  "/carta/fumanchu/plato-taypa.webp":
    "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwAgCdASoQAAsAA8BgJaACdAEfcEV8EfCyAAD+9J/c/ntBdSy9KG3kzPgtOxr4WpvzBkX87KVKxR0h2JfubTgzzOGRWtsstugkpgZ+Am6AAA==",
  "/carta/fumanchu/plato-tipakay.webp":
    "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAsAA8BgJbACdAEemwgGrwAA/tz/P3Lqzczod5rnwCjOgbt+42bzgxsB93mFB256i/pGbQJ48NF3sSbGs2lSO35D6fzbvfqWFlm3d6Ui7zQAAAA=",
  "/carta/fumanchu/plato-tortilla-lang.webp":
    "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAABQAgCdASoQAAsAA8BgJbACdH8AGZYnR0x9zIAA/u0NYRJYBpM9KDrT1zio2lXWM14woM7DeMujx96VVL8rJxSHvaOgGpv/Oo/jtAJntMwusP6DwUTeE/4Wks8AAA==",
  "/carta/fumanchu/plato-tortilla-pollo.webp":
    "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAsAA8BgJaACdAEU0FVD5IAA/vXwc7Yr9ay2zw8xeG8t2bGFEOMiS2L5g50/cXjiu1VVlI42pMLF2s8MyMMSsORPG3uLd4lsLu1tAAA=",
  "/carta/fumanchu/plato-wantanes.webp":
    "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAsAA8BgJbACdADCEF/gYAAA/vFBFLsej0wtPfNVgx6LarK7lvViauHSuznjwa++YH9bzHp+Vrip5JXJYEwJW3tbWInUpAA=",
};
